services:
  mongo:
    image: mongo:6.0
    container_name: mongo-debug
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-init:
    image: mongo:6.0
    container_name: mongo-init
    depends_on:
      - mongo
    networks:
      - mongo_network
    restart: "no"
    volumes:
      - ./init-mongo.sh:/init-mongo.sh
    entrypoint: [ "bash", "/init-mongo.sh" ]

networks:
  mongo_network:

volumes:
  mongo_data:
