services:
  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      mongo_network:
        aliases:
          - mongo-db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 5s
      retries: 5
      start_period: 10s

  mongo-init:
    image: mongo:6.0
    container_name: mongo-init
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - mongo_network
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        sleep 10 &&
        mongosh --host localhost:27017 --eval '
          rs.initiate({
            _id: "rs0",
            version: 1,
            members: [{ _id: 0, host: "localhost:27017" }]
          });
        ' &&
        echo "✅ Replica set initialized successfully!"

networks:
  mongo_network:

volumes:
  mongo_data:
