services:
  mongo:
    image: mongo:6.0
    container_name: mongo-debug
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  mongo-init:
    image: mongo:6.0
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    command: >
      bash -c "
        echo '[INFO] Initializing MongoDB Replica Set...' &&
        sleep 5 &&
        mongosh --host mongo --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          });
        ' &&
        echo '[INFO] MongoDB Replica Set Initialized Successfully!'
      "
  
volumes:
  mongo_data:
