services:
  mongo:
    image: mongo:6.0
    container_name: mongo-debug
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-init:
    image: mongo:6.0
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    entrypoint: >
      bash -c "
      echo '[INFO] 🚀 Waiting for MongoDB to be ready...';
      until mongosh --host mongo:27017 --eval 'db.runCommand({ ping: 1 })'; do
          echo '[INFO] ⏳ Waiting for MongoDB...';
          sleep 2;
      done;
      echo '[INFO] ✅ MongoDB is up. Initializing Replica Set...';
      mongosh --host mongo:27017 --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo:27017\" }]})';
      echo '[INFO] 🎉 Replica Set Initialized Successfully!';
      "

volumes:
  mongo_data:
